# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EXdsBFKUJdI4NTrUew_5GYJ1tQioEIgs
"""

pip install opencv-python

from  google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("rasm.jpg")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from  google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("/photo_2024-11-13_14-23-26.jpg")
cv2_imshow(rasm)

from  google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("/rasm2.jpg")
cv2_imshow(rasm)

from  google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("/rasm3.jpg")
cv2_imshow(rasm)

from  google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("/rasm4.jpg")
cv2_imshow(rasm)